pipeline {
 agent {
  label 'master'
 }

 parameters {
   string(defaultValue: 'abc', description: 'parameters.', name: 'paramName')
 }

 stages {
  stage('Build') {
   steps {

    println "[INFO]...........................................................................................\
           \n[INFO].. Pipeline for automating build of calculator miscroservice..\
           \n[INFO]..........................................................................................."

    script {
           println params.paramName
           }
    }
   }

  stage('Run Unit tests') {
   steps {

    println "[INFO]...........................................................................................\
           \n[INFO].. Pipeline for automating build of calculator miscroservice..\
           \n[INFO]..........................................................................................."

    script {
           println params.paramName
           }
    }
   }


 } //end stages

 post {
   cleanup {
       cleanWs()
   }
 }

} //end pipeline
